---
version: '3.5'

services:
  pyapp:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    hostname: py-app
    container_name: py-app
    env_file:
      - "vars.env"
    ports:
      - "8080:8080"
