---
version: '3.5'

services:
  pyapp:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    hostname: py-app
    container_name: py-app
    env_file:
      - "vars.env"
    ports:
      - "8080:8080"

  redis:
    image: redis:5.0-alpine
    hostname: redis-db
    container_name: redis-db
    env_file:
      - "vars.env"
    ports:
      - "6379:6379"
